merchisdk/sdk

python/menus.py
python/request.py
python/users.py
python/util/gravatar.py

remove all but one reference to the frontend/ package.

---

php/src/util/notification_type.php

the system.
This is a cleaned up version of work by @jack_loves_coding

Teach the PHP SDK about the various kinds of notifications supported by

---

php/src/country_taxes.php
php/tests/test.php

this is a cleaned up version of work by @jack_loves_coding

teach PHP SDK about CountryTax entities.

---

php/src/discounts.php
php/tests/test.php

this is a cleaned up version of work by @jack_loves_coding.

teach PHP SDK about Discount entities.

---

php/src/domain_invitations.php
php/tests/test.php

this is a cleaned up version of work by @jack_loves_coding

teach PHP SDK about domain invitation entities.

---

php/src/util/invoice_status.php

This is a cleaned up version of work by @jack_loves_coding.

Teach PHP SDK about invoice status enum.

---

python/util/s3.py
python/util/shipping_companies.py
python/util/tmp_file_store.py

uploading a file, method could return None instead of raising
the underlying exception.

Fix a bug in Python SDK where, if retries limit was reached for

---

python/util/s3.py

KeyError as it claims to rather than the internal botocore
exception.

Fix fetch_file of the S3 section of the python3 code to raise

---

python/util/s3.py

to prevent interuptions while producing backups.

Increase the number of retried allowed while fetching files so as

---

python/domains.py

for the draft preview page to work.

Add missing method `get_draft_preview_page_content` which is required

---

.coveralls.yml
.travis.yml
README.md
php/phpcs.xml
python/requirements/dev.txt

Because it seems to be quite slow, and meanwhile, codecov seems to be
adequate.

Disable coveralls.

---

python/entities.py

for pr https://github.com/Unitix/CRM-API/pull/5903

dump_to_json_str can handle html escape by itself

---

python/util/roles.py

related https://github.com/Unitix/CRM-API/pull/5941

reduce duplicate code for business accounts

---

python/domain_tags.py
python/jobs.py

Add backref relations to domain tags to allow access from either side of

---

.travis.yml

composer config directory has mysteriously moved, despite most relevent
version numbers being the same.

Fix travisCI build.

---

python/requirements/dev.txt

Update to newer versions of requests and openssl.

---

python/util/s3.py

pagination and thus did not actually return all keys

fix a bug in S3Bucket.all_keys where it did not account for all

---

typescript/src/entities/categories.test.ts
typescript/src/entities/categories.ts
typescript/src/entities/products.test.ts
typescript/src/entities/products.ts
typescript/src/entity.ts
typescript/src/merchi.ts
typescript/src/request.test.ts
typescript/src/request.ts

demonstrate that it works by allowing embed descriptors in fetch requests.

add a method of teaching typescript about non-scalar relationships.

---

typescript/src/entities/product.test.ts
typescript/src/request.test.ts
typescript/src/test_util.ts

not every typescript test has to use an override url, only one

---

typescript/src/entities/product.test.ts
typescript/src/entity.ts
typescript/src/merchi.ts

typescript sdk list function supports all arguments that the backend

---

typescript/src/entities/category.ts
typescript/src/entities/domain.ts
typescript/src/entities/product.test.ts
typescript/src/entities/product.ts
typescript/src/entity.ts

not data that is already directly from the server.

update typescript sdk to only send changed data back to the server,

---

typescript/src/entities/product.ts
typescript/src/entity.ts

at beginning I thought I found a bug, until I nearly finish this pr I notice the although fromJson and fromJsonList is slightly different compare to merchi.js version. It works fine.
However I still prefer the original version of fromJson which expect {json data} rather than {singular_name: json_data}.

refactor fromJson function make it more close to js sdk

---

typescript/src/test_util.ts
typescript/src/util/validation.test.ts
typescript/src/util/validation.ts

port merchi js is undefined or null ot ts sdk

port is undefine or null from merchi js sdk to ts sdk

---

typescript/src/entity.ts

According to the current protocol, file form data should not include the
'prefix' section.

Fix file upload in TS SDK.

---

typescript/src/entity.ts

Basically I don't understand javascript prototype/inheritance chain stuff
very well any more, and I can't figure out how to set up prototype so
that instanceof works without breaking other things, so I just reach
into the prototype and compare it directly against a known-good version.
seems to work ok...

Hack to get nullable items working.

---

typescript/src/entities/product.test.ts
typescript/src/entity.ts

would not be requested for deletion.

Bug fix for ts sdk where under some circumstances nulled out entities

---

python/domains.py

py sdk: Domains.get_domain_by_name accepts an argument giving the domain

---

python/domains.py

Revert "py sdk: Domains.get_domain_by_name accepts an argument giving the domain"

---

python/subscription_plans.py
python/util/errors.py
typescript/src/entities/subscription_plan.ts

Teach SDK that SubscriptionPlans can be shown publically or not.

---

python/discount.py
python/discount_groups.py
python/products.py
python/util/discount_types.py
python/variations.py
typescript/src/constants/discount_types.test.ts
typescript/src/constants/discount_types.ts
typescript/src/entities/discount.test.ts
typescript/src/entities/discount.ts
typescript/src/entities/discount_group.test.ts
typescript/src/entities/discount_group.ts
typescript/src/entities/product.ts
typescript/src/entities/variation_field.ts
typescript/src/entities/variation_fields_option.ts
typescript/src/merchi.ts

Reverts merchisdk/sdk#409
for discounts develop under this pr

Revert "Revert "Extend discounts""

---

javascript/user.js

Revert "fix each/foreach typo"

---

javascript/user.js

Revert "fix enrolled domains"

---

javascript/address.js
javascript/company.js
javascript/domain.js
javascript/invoice.js
javascript/job.js
javascript/merchi_file.js
javascript/product.js
javascript/roles.js
javascript/session.js
javascript/user.js

fix some places that where using javascript Request and Set instead of

---

javascript/merchi_file.js
python/files.py
typescript/src/entities/file.ts

Revert "add server_url to file ent"
